# Generated by Django 4.0.4 on 2022-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_categoria_post_f_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
