# Generated by Django 4.0.4 on 2022-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_categoria_nombre_alter_post_titulo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150, verbose_name='contenido')),
            ],
        ),
    ]
