# Generated by Django 4.0.4 on 2022-05-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='f_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
