# Generated by Django 4.0.4 on 2022-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentario_f_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
