# Generated by Django 4.0.4 on 2022-05-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_comentario_f_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='f_post_id',
            new_name='idPost',
        ),
    ]
