# Generated by Django 4.0.4 on 2022-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comentario_idpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='f_categoria',
            field=models.IntegerField(),
        ),
    ]
