# Generated by Django 4.0.4 on 2022-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_f_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='idPost',
            field=models.IntegerField(),
        ),
    ]
