# Generated by Django 4.0.4 on 2022-05-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_comentario_idpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='idPost',
            new_name='f_post_id',
        ),
    ]
