# Generated by Django 4.0.4 on 2022-05-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_idpost_comentario_f_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='especialidad',
            new_name='au_especialidad',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='au_nombre',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='ca_descripcion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='ca_nombre',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='com_contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fechaComentario',
            new_name='com_fechaComentario',
        ),
    ]
